"""add api.verb

Revision ID: 2f9356e7c878
Revises: 387b7ab0db61
Create Date: 2015-03-21 21:21:45.693215

"""

# revision identifiers, used by Alembic.
revision = '2f9356e7c878'
down_revision = '387b7ab0db61'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api', sa.Column('verb', sa.String(length=7), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api', 'verb')
    ### end Alembic commands ###
