"""add api.status_code

Revision ID: 387b7ab0db61
Revises: 6aaeffe2b58
Create Date: 2015-03-21 20:20:49.839596

"""

# revision identifiers, used by Alembic.
revision = '387b7ab0db61'
down_revision = '6aaeffe2b58'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api', sa.Column('arguments', postgresql.JSON(), nullable=True))
    op.add_column('api', sa.Column('body', postgresql.JSON(), nullable=True))
    op.add_column('api', sa.Column('headers', postgresql.JSON(), nullable=True))
    op.add_column('api', sa.Column('status_code', sa.Integer(), nullable=True))
    op.drop_column('api', 'response_body')
    op.drop_column('api', 'request_args')
    op.drop_column('api', 'response_headers')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api', sa.Column('response_headers', postgresql.JSON(), autoincrement=False, nullable=True))
    op.add_column('api', sa.Column('request_args', postgresql.JSON(), autoincrement=False, nullable=True))
    op.add_column('api', sa.Column('response_body', postgresql.JSON(), autoincrement=False, nullable=True))
    op.drop_column('api', 'status_code')
    op.drop_column('api', 'headers')
    op.drop_column('api', 'body')
    op.drop_column('api', 'arguments')
    ### end Alembic commands ###
